### PR TITLE
Add github actions to deploy on tailscale

### LINKED ISSUE #16: feat: GitHub actions for deployment
### Tasks
- Create **GitHub actions** to deploy the bot as soon as a commit is made in the `main` branch.

### PR DESCRIPTION
**Pull request by HarshDobariya79**
This PR closes #16

### CODE REVIEW

**Review by h3110Fr13nd — DISMISSED** [review]
Looks good to me.

**Comment by HarshDobariya79** [comment]
The branch is set to **release** to avoid deploying minor changes.

**Comment by h3110Fr13nd** [comment]
Nice Work with removing previous images as well after container creating.

**Review by h3110Fr13nd — APPROVED** [review]

**Comment by h3110Fr13nd** [comment]
Remember to create a release branch at convenience.

**Pull request merged**
